### ISSUE TITLE
Bullet is not completely centered on tank turret.

### ISSUE THREAD

**Issue by aec1140** [aec1140/D-TOM#17]
@ToothlessHawkins At some point, the bullet needs to be centered to the turret as it exits. As of right now it is close enough, but when a new model is imported to scale, we should fix the issue.

**Comment by ToothlessHawkins** [comment]
I'm pretty sure I just fixed the issue. The gameObject that spawns the bullet was a little off, but I noticed that the target on the UI was off center. Fixing that and moving the gameObject f over a little bit seems to have fixed the issue, though the target is not very effective with the bullet drop.

**Comment by aec1140** [comment]
Bullet drop is would be a separate issue. Closing this bug as fixed.
