### ISSUE TITLE
UI bug

### ISSUE THREAD

**Issue by ToothlessHawkins** [aec1140/D-TOM#89]
While holding Left Bumper, if the player attempts to swap roles, the active UI panel will not fall

**Comment by ToothlessHawkins** [comment]
This bug is most likely due to the fact that when a role is swapped, the panel for that role will stay in w/e state it was in when it was swapped away from. In order to fix this, a panel should be reset when swapped away from.

**Comment by aec1140** [comment]
This will get fixed when acknowledgment is required
